include "include/test.t"

var v : int<4>;
v.x = 4;
v.y = 3;
v.z = 2;
v.w = 1;
Test.Expect(v.x == 4);
Test.Expect(v.y == 3);
Test.Expect(v.z == 2);
Test.Expect(v.w == 1);
v.xz = int<2>{1, 3};
v.wy = int<2>{4, 2};
Test.Expect(v.x == 1);
Test.Expect(v.y == 2);
Test.Expect(v.z == 3);
Test.Expect(v.w == 4);
v.wzxy = int<4>{8, 7, 5, 6};
Test.Expect(v.x == 5);
Test.Expect(v.y == 6);
Test.Expect(v.z == 7);
Test.Expect(v.w == 8);

var pv = new int<4>;
pv.x = 4;
pv.y = 3;
pv.z = 2;
pv.w = 1;
Test.Expect(pv.x == 4);
Test.Expect(pv.y == 3);
Test.Expect(pv.z == 2);
Test.Expect(pv.w == 1);
pv.xz = int<2>{1, 3};
pv.wy = int<2>{4, 2};
Test.Expect(pv.x == 1);
Test.Expect(pv.y == 2);
Test.Expect(pv.z == 3);
Test.Expect(pv.w == 4);
pv.wzxy = int<4>{8, 7, 5, 6};
Test.Expect(pv.x == 5);
Test.Expect(pv.y == 6);
Test.Expect(pv.z == 7);
Test.Expect(pv.w == 8);
