// Copyright 2025 The Toucan Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

namespace Toucan {
extern bool exitOnAbort;
class NodeVector;
class Stmts;
class TypeTable;
// This function will be generated by the bindings generator.
void InitAPI(NodeVector* nodes, TypeTable* types, Stmts* rootStmts);
};  // namespace Toucan
